### ISSUE TITLE
njupt.Card 无法正常使用

### ISSUE THREAD

**Issue by shaoye** [gaoliang/NJUPT-API#12]
https://github.com/gaoliang/NJUPT-API/blob/3c6d458a526dab77241805f65421abf483552ef7/njupt/card.py#L32

`URLs.HOST`

> 500 Internal Privoxy Error

**Comment by gaoliang** [comment]
关停了。。 比Google Plus关的还暴力

**Comment by gaoliang** [comment]
恢复了
